env:
  es2022: true
  node: true
extends:
  - airbnb-base
  - airbnb-typescript/base
ignorePatterns:
  - dist/
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
rules:
  no-console: 'off'
